### ISSUE TITLE
Fibaro FGR222 reporting Unknown value which causes issues in Home Assistant

### ISSUE THREAD

**Issue by foxy82** [zwave-js/zwave-js-server#129] opened 2021-02-21 17:20 UTC
I've originally reported this in Home Assistant here: https://github.com/home-assistant/core/issues/46857

After some debugging with freshcoat on Discord we can see that ZWaveJS is genuinely reporting this value.  (Logs below) so the question is - is that correct? Should HA deal with unknown or should ZWaveJS not be reporting this?

Value was "unknown" in Zwave JS interface: 

![image](https://user-images.githubusercontent.com/7756020/108632857-ec036b80-7468-11eb-9cde-cd7f79747d61.png)

So I attempted to set it to 1 but it immediately set it back to unknown

zwavejs2mqtt.log:

```txt
2021-02-21 17:05:52.071 INFO ZWAVE: Calling api writeValue with args: [
  {
    nodeId: 39,
    commandClass: 38,
    endpoint: 0,
    property: 'targetValue'
  },
  1,
  [length]: 2
]
2021-02-21 17:05:52.072 INFO ZWAVE: Writing 1 to 39-38-0-targetValue
2021-02-21 17:05:52.107 INFO ZWAVE: Node 39: value updated: 38-0-currentValue unknown => 1
2021-02-21 17:05:52.109 INFO ZWAVE: Success zwave api call writeValue { success: true, message: 'Success zwave api call', result: undefined }
2021-02-21 17:05:53.274 INFO ZWAVE: Node 39: metadata updated: 49-0-Power
2021-02-21 17:05:53.279 INFO ZWAVE: Node 39: value updated: 49-0-Power 0 => 24.5
2021-02-21 17:05:57.152 INFO ZWAVE: Node 39: value updated: 38-0-currentValue 1 => unknown
2021-02-21 17:06:00.381 INFO ZWAVE: Node 39: metadata updated: 49-0-Power
2021-02-21 17:06:00.384 INFO ZWAVE: Node 39: value updated: 49-0-Power 24.5 => 0
2021-02-21 17:06:02.950 INFO ZWAVE: Node 39: metadata updated: 49-0-Power
2021-02-21 17:06:02.953 INFO ZWAVE: Node 39: value updated: 49-0-Power 0 => 13.3
2021-02-21 17:06:07.016 INFO ZWAVE: Node 39: metadata updated: 49-0-Power
2021-02-21 17:06:07.019 INFO ZWAVE: Node 39: value updated: 49-0-Power 13.3 => 11.9
2021-02-21 17:06:11.810 INFO ZWAVE: Node 39: value updated: 38-0-currentValue unknown => unknown
2021-02-21 17:06:11.828 INFO ZWAVE: Node 39: metadata updated: 49-0-Power
2021-02-21 17:06:11.829 INFO ZWAVE: Node 39: value updated: 49-0-Power 11.9 => 0
```

zwavejs_354.log:

```txt
17:05:52.077 SERIAL » 0x010a001327032601012505c4                                          (12 bytes)
17:05:52.078 DRIVER » [Node 039] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      5
                      └─[MultilevelSwitchCCSet]
                          target value: 1
17:05:52.079 SERIAL « [ACK]                                                                   (0x06)
17:05:52.086 SERIAL « 0x0104011301e8                                                       (6 bytes)
17:05:52.086 SERIAL » [ACK]                                                                   (0x06)
17:05:52.086 DRIVER « [RES] [SendData]
                        was sent: true
17:05:52.103 SERIAL « 0x0107001305000002ec                                                 (9 bytes)
17:05:52.103 SERIAL » [ACK]                                                                   (0x06)
17:05:52.104 DRIVER « [REQ] [SendData]
                        callback id:     5
                        transmit status: OK
17:05:52.106 CNTRLR   [Node 039] [~] [Multilevel Switch] currentValue: "unknown" => 1   [Endpoint 0]
17:05:53.271 SERIAL « 0x010c00040027063105042200f531                                      (14 bytes)
17:05:53.272 CNTRLR   [Node 039] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
17:05:53.277 CNTRLR   [Node 039] [~] [Multilevel Sensor] Power: 0 => 24.5               [Endpoint 0]
17:05:53.280 SERIAL » [ACK]                                                                   (0x06)
17:05:53.281 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSensorCCReport]
                          type:  Power
                          scale: Watt
                          value: 24.5
17:05:57.113 SERIAL » 0x01090013270226022506c7                                            (11 bytes)
17:05:57.114 DRIVER » [Node 039] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      6
                      └─[MultilevelSwitchCCGet]
17:05:57.116 SERIAL « [ACK]                                                                   (0x06)
17:05:57.122 SERIAL « 0x0104011301e8                                                       (6 bytes)
17:05:57.122 SERIAL » [ACK]                                                                   (0x06)
17:05:57.123 DRIVER « [RES] [SendData]
                        was sent: true
17:05:57.139 SERIAL « 0x0107001306000002ef                                                 (9 bytes)
17:05:57.140 SERIAL » [ACK]                                                                   (0x06)
17:05:57.141 DRIVER « [REQ] [SendData]
                        callback id:     6
                        transmit status: OK
17:05:57.149 SERIAL « 0x010900040027032603fe0d                                            (11 bytes)
17:05:57.151 CNTRLR   [Node 039] [~] [Multilevel Switch] currentValue: 1 => "unknown"   [Endpoint 0]
17:05:57.153 SERIAL » [ACK]                                                                   (0x06)
17:05:57.154 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSwitchCCReport]
                          current value: unknown
17:06:00.379 SERIAL « 0x010c0004002706310504220000c4                                      (14 bytes)
17:06:00.380 CNTRLR   [Node 039] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
17:06:00.383 CNTRLR   [Node 039] [~] [Multilevel Sensor] Power: 24.5 => 0               [Endpoint 0]
17:06:00.385 SERIAL » [ACK]                                                                   (0x06)
17:06:00.387 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSensorCCReport]
                          type:  Power
                          scale: Watt
                          value: 0
17:06:02.947 SERIAL « 0x010c000400270631050422008541                                      (14 bytes)
17:06:02.948 CNTRLR   [Node 039] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
17:06:02.952 CNTRLR   [Node 039] [~] [Multilevel Sensor] Power: 0 => 13.3               [Endpoint 0]
17:06:02.954 SERIAL » [ACK]                                                                   (0x06)
17:06:02.955 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSensorCCReport]
                          type:  Power
                          scale: Watt
                          value: 13.3
17:06:07.009 SERIAL « 0x010c0004002706310504220077b3                                      (14 bytes)
17:06:07.014 CNTRLR   [Node 039] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
17:06:07.017 CNTRLR   [Node 039] [~] [Multilevel Sensor] Power: 13.3 => 11.9            [Endpoint 0]
17:06:07.020 SERIAL » [ACK]                                                                   (0x06)
17:06:07.021 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSensorCCReport]
                          type:  Power
                          scale: Watt
                          value: 11.9
17:06:11.807 SERIAL « 0x010900040027032603fe0d                                            (11 bytes)
17:06:11.808 CNTRLR   [Node 039] [~] [Multilevel Switch] currentValue: "unknown" => "un [Endpoint 0]
                      known"
17:06:11.811 SERIAL » [ACK]                                                                   (0x06)
17:06:11.813 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSwitchCCReport]
                          current value: unknown
17:06:11.826 SERIAL « 0x010c0004002706310504220000c4                                      (14 bytes)
17:06:11.827 CNTRLR   [Node 039] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
17:06:11.828 CNTRLR   [Node 039] [~] [Multilevel Sensor] Power: 11.9 => 0               [Endpoint 0]
17:06:11.829 SERIAL » [ACK]                                                                   (0x06)
17:06:11.830 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSensorCCReport]
                          type:  Power
                          scale: Watt
                          value: 0

```

**Comment by foxy82** [comment] 2021-02-22 09:20
I looked through my config in ZWaveJS for this and compared it to my working device and I found that this is set to 0 on my working one and as you can see the value is outside the range that ZWaveJS claims it should be in:

![image](https://user-images.githubusercontent.com/7756020/108687242-60ccb900-74ee-11eb-9316-2ba90b028017.png)

I set this to 0 and that looks to have removed the unknown at the moment. However as you can see from my screen shot it has reverted back to 254.

```
2021-02-22 09:04:13.209 INFO ZWAVE: Calling api writeValue with args: [
  {
    nodeId: 39,
    commandClass: 145,
    endpoint: 0,
    property: 'fibaro',
    propertyKey: 'venetianBlindsPosition'
  },
  2,
  [length]: 2
]
2021-02-22 09:04:13.210 INFO ZWAVE: Writing 2 to 39-145-0-fibaro-venetianBlindsPosition
2021-02-22 09:04:13.246 INFO ZWAVE: Success zwave api call writeValue { success: true, message: 'Success zwave api call', result: undefined }
2021-02-22 09:04:14.368 INFO ZWAVE: Node 39: metadata updated: 49-0-Power
2021-02-22 09:04:14.371 INFO ZWAVE: Node 39: value updated: 49-0-Power 0 => 25.1
2021-02-22 09:04:17.214 INFO ZWAVE: Node 27: metadata updated: 49-1-Power
2021-02-22 09:04:17.217 INFO ZWAVE: Node 27: value updated: 49-1-Power 0 => 0
2021-02-22 09:04:23.495 INFO ZWAVE: Node 39: value updated: 38-0-currentValue unknown => 99
2021-02-22 09:04:23.512 INFO ZWAVE: Node 39: metadata updated: 49-0-Power
2021-02-22 09:04:23.513 INFO ZWAVE: Node 39: value updated: 49-0-Power 25.1 => 0
2021-02-22 09:04:32.287 DEBUG SOCKET: Event ZWAVE_API emitted to VrcMDxkJFuHVm-3-AAAT
2021-02-22 09:04:32.288 INFO ZWAVE: Calling api writeValue with args: [
  {
    nodeId: 39,
    commandClass: 145,
    endpoint: 0,
    property: 'fibaro',
    propertyKey: 'venetianBlindsPosition'
  },
  0,
  [length]: 2
]
2021-02-22 09:04:32.289 INFO ZWAVE: Writing 0 to 39-145-0-fibaro-venetianBlindsPosition
2021-02-22 09:04:32.325 INFO ZWAVE: Success zwave api call writeValue { success: true, message: 'Success zwave api call', result: undefined }
2021-02-22 09:04:33.453 INFO ZWAVE: Node 39: metadata updated: 49-0-Power
2021-02-22 09:04:33.454 INFO ZWAVE: Node 39: value updated: 49-0-Power 0 => 13.9
2021-02-22 09:04:35.277 INFO ZWAVE: Node 25: value updated: 50-1-value-65537 4 => 4
2021-02-22 09:04:35.280 INFO ZWAVE: Node 25: value updated: 50-1-deltaTime-65537 0 => 0
2021-02-22 09:04:36.034 INFO APP: GET /health/zwave 200 1.073 ms - 1875
2021-02-22 09:04:37.513 INFO ZWAVE: Node 39: metadata updated: 49-0-Power
2021-02-22 09:04:37.514 INFO ZWAVE: Node 39: value updated: 49-0-Power 13.9 => 12.2
2021-02-22 09:04:45.638 INFO ZWAVE: Node 39: metadata updated: 49-0-Power
2021-02-22 09:04:45.639 INFO ZWAVE: Node 39: value updated: 49-0-Power 12.2 => 0
2021-02-22 09:04:47.029 INFO ZWAVE: Node 39: value updated: 38-0-currentValue 99 => 0
2021-02-22 09:04:47.048 INFO ZWAVE: Node 39: metadata updated: 49-0-Power
2021-02-22 09:04:47.049 INFO ZWAVE: Node 39: value updated: 49-0-Power 0 => 0
```

```
09:04:00.094 CNTRLR   [Node 039] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
09:04:00.096 CNTRLR   [Node 039] [~] [Multilevel Sensor] Power: 0 => 0                  [Endpoint 0]
09:04:00.098 SERIAL » [ACK]                                                                   (0x06)
09:04:00.100 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSensorCCReport]
                          type:  Power
                          scale: Watt
                          value: 0
09:04:13.216 SERIAL » 0x010f0013270891010f260102020025e5b4                                (17 bytes)
09:04:13.216 DRIVER » [Node 039] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      229
                      └─[FibaroVenetianBlindCCSet]
                          position: 2
09:04:13.218 SERIAL « [ACK]                                                                   (0x06)
09:04:13.224 SERIAL « 0x0104011301e8                                                       (6 bytes)
09:04:13.225 SERIAL » [ACK]                                                                   (0x06)
09:04:13.225 DRIVER « [RES] [SendData]
                        was sent: true
09:04:13.243 SERIAL « 0x01070013e50000020c                                                 (9 bytes)
09:04:13.243 SERIAL » [ACK]                                                                   (0x06)
09:04:13.244 DRIVER « [REQ] [SendData]
                        callback id:     229
                        transmit status: OK
09:04:14.363 SERIAL « 0x010c00040027063105042200fb3f                                      (14 bytes)
09:04:14.365 CNTRLR   [Node 039] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
09:04:14.369 CNTRLR   [Node 039] [~] [Multilevel Sensor] Power: 0 => 25.1               [Endpoint 0]
09:04:14.371 SERIAL » [ACK]                                                                   (0x06)
09:04:14.372 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSensorCCReport]
                          type:  Power
                          scale: Watt
                          value: 25.1
09:04:17.211 SERIAL « 0x01100004001b0a600d010131050422000085                              (18 bytes)
09:04:17.212 CNTRLR   [Node 027] [Multilevel Sensor] Power: metadata updated            [Endpoint 1]
09:04:17.215 CNTRLR   [Node 027] [~] [Multilevel Sensor] Power: 0 => 0                  [Endpoint 1]
09:04:17.217 SERIAL » [ACK]                                                                   (0x06)
09:04:17.220 DRIVER « [Node 027] [REQ] [ApplicationCommand]
                      └─[MultiChannelCCCommandEncapsulation]
                        │ source:      1
                        │ destination: 1
                        └─[MultilevelSensorCCReport]
                            type:  Power
                            scale: Watt
                            value: 0
09:04:23.491 SERIAL « 0x0109000400270326036390                                            (11 bytes)
09:04:23.493 CNTRLR   [Node 039] [~] [Multilevel Switch] currentValue: "unknown" => 99  [Endpoint 0]
09:04:23.496 SERIAL » [ACK]                                                                   (0x06)
09:04:23.498 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSwitchCCReport]
                          current value: 99
09:04:23.510 SERIAL « 0x010c0004002706310504220000c4                                      (14 bytes)
09:04:23.511 CNTRLR   [Node 039] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
09:04:23.512 CNTRLR   [Node 039] [~] [Multilevel Sensor] Power: 25.1 => 0               [Endpoint 0]
09:04:23.513 SERIAL » [ACK]                                                                   (0x06)
09:04:23.514 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSensorCCReport]
                          type:  Power
                          scale: Watt
                          value: 0
09:04:32.294 SERIAL » 0x010f0013270891010f260102000025e6b5                                (17 bytes)
09:04:32.294 DRIVER » [Node 039] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      230
                      └─[FibaroVenetianBlindCCSet]
                          position: 0
09:04:32.296 SERIAL « [ACK]                                                                   (0x06)
09:04:32.302 SERIAL « 0x0104011301e8                                                       (6 bytes)
09:04:32.303 SERIAL » [ACK]                                                                   (0x06)
09:04:32.303 DRIVER « [RES] [SendData]
                        was sent: true
09:04:32.321 SERIAL « 0x01070013e60000020f                                                 (9 bytes)
09:04:32.321 SERIAL » [ACK]                                                                   (0x06)
09:04:32.322 DRIVER « [REQ] [SendData]
                        callback id:     230
                        transmit status: OK
09:04:33.449 SERIAL « 0x010c000400270631050422008b4f                                      (14 bytes)
09:04:33.451 CNTRLR   [Node 039] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
09:04:33.454 CNTRLR   [Node 039] [~] [Multilevel Sensor] Power: 0 => 13.9               [Endpoint 0]
09:04:33.455 SERIAL » [ACK]                                                                   (0x06)
09:04:33.456 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSensorCCReport]
                          type:  Power
                          scale: Watt
                          value: 13.9
09:04:37.512 SERIAL « 0x010c000400270631050422007abe                                      (14 bytes)
09:04:37.512 CNTRLR   [Node 039] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
09:04:37.514 CNTRLR   [Node 039] [~] [Multilevel Sensor] Power: 13.9 => 12.2            [Endpoint 0]
09:04:37.514 SERIAL » [ACK]                                                                   (0x06)
09:04:37.515 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSensorCCReport]
                          type:  Power
                          scale: Watt
                          value: 12.2
09:04:45.635 SERIAL « 0x010c0004002706310504220000c4                                      (14 bytes)
09:04:45.636 CNTRLR   [Node 039] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
09:04:45.639 CNTRLR   [Node 039] [~] [Multilevel Sensor] Power: 12.2 => 0               [Endpoint 0]
09:04:45.640 SERIAL » [ACK]                                                                   (0x06)
09:04:45.641 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSensorCCReport]
                          type:  Power
                          scale: Watt
                          value: 0
09:04:47.028 SERIAL « 0x01090004002703260300f3                                            (11 bytes)
09:04:47.028 CNTRLR   [Node 039] [~] [Multilevel Switch] currentValue: 99 => 0          [Endpoint 0]
09:04:47.030 SERIAL » [ACK]                                                                   (0x06)
09:04:47.030 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSwitchCCReport]
                          current value: 0
09:04:47.047 SERIAL « 0x010c0004002706310504220000c4                                      (14 bytes)
09:04:47.048 CNTRLR   [Node 039] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
09:04:47.049 CNTRLR   [Node 039] [~] [Multilevel Sensor] Power: 0 => 0                  [Endpoint 0]
09:04:47.049 SERIAL » [ACK]                                                                   (0x06)
09:04:47.050 DRIVER « [Node 039] [REQ] [ApplicationCommand]
                      └─[MultilevelSensorCCReport]
                          type:  Power
                          scale: Watt
                          value: 0

```

**Comment by robertsLando** [comment] 2021-02-22 09:23
@AlCalzone ? Is that unknown something new?

**Comment by AlCalzone** [comment] 2021-02-22 10:14
No, it has always been there - we've just never experienced it (this came up in the HA dev discord too).
Some devices can report an unknown current value. Currently this is reflected with the value `"unknown"` to distinguish it from a missing value, but I'm thinking of dropping this distiction.

**Comment by MartinHjelmare** [comment] 2021-02-22 10:29
We're going to handle this in our Python library as long as upstream keeps it around.

**Comment by robertsLando** [comment] 2021-02-22 10:34
@MartinHjelmare Could I close this and point the user on hass repo so?

**Comment by foxy82** [comment] 2021-02-22 10:37
Can you just confirm from the logs above that my device reported unknown? and also that the parameter that seems related to the issue where there is a 254 in a field between 0-99 isn't a bug in ZWaveJS server?

**Comment by robertsLando** [comment] 2021-02-22 10:39
The value reports unknown, the problem is that value isn't handled correctly on hass side (yet)

**Comment by foxy82** [comment] 2021-02-22 10:41
Ok so is the ZWaveJS handling this device properly - with the note about the value that ZWavwJS says can only be between 0 and 99 being set to 254? I can't see the 254 obviously coming from the device in my logs above?

**Comment by MartinHjelmare** [comment] 2021-02-22 10:43
We've already fixed the exception in the Python library and it will go out in the next release.

The underlying issue with an unknown value we can't fix since that comes from the device and Z-Wave JS.

**Closed by MartinHjelmare** 2021-02-22 10:43 UTC

**Comment by foxy82** [comment] 2021-02-22 10:46
Ok I'll open another issue for the dodgy 254 value so it doen'st get confused with the unknown - thanks.

**Comment by MartinHjelmare** [comment] 2021-02-22 10:49
Please open issues first in Home Assistant core repo. The server in this repo is just a transport intermediate and rarely involved in device specific issues.
