### ISSUE TITLE
Error controlling cover (rolling shutters)

### ISSUE THREAD

**Issue by npoirey** [zwave-js/zwave-js-server#91] opened 2021-02-07 19:52 UTC
Hi,

I'm sorry If I'm not on the correct repo, because I honestly don't understand the root cause of the error.

Basically, I successfully added a fibaro rolling sutter 3 micro module on Home Assistant, via zwavejs integration.
It seems that can read instantaneous power consumption when I manually activate it (using the wall switch)
Howerver, when tyring to control it from the dashboard, I get an error toast saying 

`"Failed to call service cover/close_cover. None"`

Stacktrace in HA logs is :

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/zwave_js/cover.py:88
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:41:48 PM (3 occurrences)
Last logged: 8:48:30 PM
[547637941104] None

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/cover.py", line 88, in async_close_cover
    await self.info.node.async_set_value(target_value, PRESS_BUTTON)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 248, in async_set_value
    val = self.values[val]
KeyError: None
```

I tried to change log level to have a little more traces but it didn't change anything.
If I go see the zwavejs supervisor logs, I see nothing suspicious.

I'm very new the the Home Assistant world so I may be missing something completely obvious...

PS : I tried using a zwave light bulb, I could turn it on or off correctly (even if it's slow and sometimes flaky, I don't get an error in logs)

**Comment by MartinHjelmare** [comment] 2021-02-08 08:19
Duplicate of https://github.com/home-assistant/core/issues/45922

**Closed by MartinHjelmare** 2021-02-08 08:19 UTC
